### ISSUE TITLE
Item long click not supported?

### ISSUE THREAD

**Issue by ajenter** [StephenVinouze/AdvancedRecyclerView#2]
Hi Stephen, thanks for a great library! 
I want to activate multichoice mode upon long click (like ListView did), however
the method "onItemLongClick" in ClickCallback is not overridable (doesn't have "open" qualifier) and is fixed to simply return false.
Is this by design or just an oversight?
Thanks!

**Comment by StephenVinouze** [comment]
Hi @ajenter.

Thanks for reporting this! It is obviously an oversight as there is no value having this method always returning false. Surely an regression while porting from Java to Kotlin. Originally I designed this callback with a default behavior for the long click as we mostly need to implement the `onClick` method. Btw I did the same mistake in the `GestureCallback` class to enable an item to be swipable/movable.

Will do a quick fix soon ;)

**Comment by ajenter** [comment]
Stephen, huge thanks for your reply! I've created a pull request to fix the issue so that you need to do less :)
(I'm not very experienced with GitHub yet, so sorry if something is not correct)

**Comment by StephenVinouze** [comment]
Merged and released ;)

**Comment by ajenter** [comment]
Cool, thanks a lot!
I want to say that I really like the structure of the library, and the documentation is very clear.
Please keep up the good work!
