### ISSUE TITLE
Section and Pagination?

### ISSUE THREAD

**Issue by thecodeside** [StephenVinouze/AdvancedRecyclerView#4]
Will be supported section and pagination in one recycler view?
Currently when we use adapter.setItems(list, page) we end up with items only from last page

**Comment by StephenVinouze** [comment]
Hi @iarchii 
Pagination for a sectioned list is not planned to be supported. It would break the pagination pattern as it would require the list to be reordered every time a new page will be loaded into the list.
But if you come up with an idea feel free to fork the lib and implement it, I will look into it with great interest ;)

**Comment by thecodeside** [comment]
I've done it in one of my projects but I had to make a lot of assumptions.
The most important one is that section could be only on first page. 
On the next page everything was added to last section. 
It worked for my case, but it isn't general.

So yeah it's hard to do correct pagination with sections.

**Comment by StephenVinouze** [comment]
So basically if you're going that way I would definitively recommend that you use the `pagination` module of this library (not the `section` one) and add your own item types to handle your sections ;)
