### ISSUE TITLE
Add support for putting all items in a section on a single background (e.g. card)

### ISSUE THREAD

**Issue by marcardar** [StephenVinouze/AdvancedRecyclerView#5]
I don't think this is currently possible (or even achievable without major refactoring) but I want to do something like in Google Inbox, where the items of each section are grouped onto a single background (e.g. CardView).

**Comment by StephenVinouze** [comment]
Hi @marcardar,
As you guessed it is possible to do such thing although not impossible but would involve some annoying code to detect the beginning and the end of each section to draw the background behind but I wouldn't recommend it.
For such thing I would recommend to build your own solution that fits this need as sectioning doesn't have to be that difficult if you just need to declare different viewtypes ;)
This library mostly intends to tacle the most common patterns to speed up your development.
I took advantage to upgrade kotlin library and clean a bit the library accordingly to release a patch version `2.0.2` :)
I wish you good luck!

**Comment by marcardar** [comment]
Thanks Stephen. For some reason, I can't see the commits corresponding to 2.0.2. Any ideas?

**Comment by StephenVinouze** [comment]
Indeed I messed up with my commit. Added another tag `2.0.3` ;)
